### ISSUE TITLE
建议中文排版参考统一的排版规范

### ISSUE THREAD

**Issue by chongyi** [huangjj27/async-book#13]
[《中文文案排版指北》 https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.zh-CN.md](https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.zh-CN.md)

因为我看翻译结果中有些排版还是比较随性 😂

**Comment by huangjj27** [comment]
> 有些排版还是比较随性 😂

因为目前使用的GitLocalize来进行翻译对比校对，格式要按照英文版的来， 否则对应不上，请见谅！后续我们会改进的

**Comment by huangjj27** [comment]
另外，关于文中有多处交替出现 `Future` 和 “future” ，也是按照英文原文的意思，前者指特质（trait），后者指实现了该特质的类型。

**Comment by huangjj27** [comment]
重新翻译，更新了排版。
