### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by Nugine** [huangjj27/async-book#14]
[src_zh/02_execution/01_chapter.md](https://raw.githubusercontent.com/huangjj27/async-book/master/src_zh/02_execution/01_chapter.md) 第 7 行  “数钱”-> “书签”

**Comment by Nugine** [comment]
[src_zh/02_execution/02_future.md](https://raw.githubusercontent.com/huangjj27/async-book/master/src_zh/02_execution/02_future.md) 第 48 行  "selF" -> "self"

**Comment by Nugine** [comment]
[src_zh/02_execution/05_io.md](https://raw.githubusercontent.com/huangjj27/async-book/master/src_zh/02_execution/05_io.md) 第 13 行 “柯杜师”-> “可读时”

**Comment by chirsz-ever** [comment]
[src_zh/03_async_await/01_chapter.md] 第 56 行 “切花道”-> “切换到”

**Comment by chirsz-ever** [comment]
[src_zh/01_getting_started/05_http_server_example.md](https://github.com/huangjj27/async-book/master/src_zh/01_getting_started/05_http_server_example.md) 第 1 行 “建议” -> “建立”
