### ISSUE TITLE
异步书中的代码示例注释翻译为中文

### ISSUE THREAD

**Issue by quasipaa** [huangjj27/async-book#3]
代码注释为讲述实现方式和思路的主要方式

**Comment by quasipaa** [comment]
以将所有代码注释翻译为中文，等待勘误审查;

**Comment by huangjj27** [comment]
今天准备理一下分支的事情，先合并了， 然后再审查。

**Comment by huangjj27** [comment]
翻译更新了，你看看是否需要重新将注释翻译成中文？ 其实我觉得将主体文本翻译弄得更通顺会更好。

**Comment by quasipaa** [comment]
> 翻译更新了，你看看是否需要重新将注释翻译成中文？ 其实我觉得将主体文本翻译弄得更通顺会更好。

弄得白话一点可能会丢失原始语义，这个还需要重新考虑，这个问题当时翻译的时候就想到了，但是我发现弄通俗点会不能很准确表达原文中的相关词汇
