### ISSUE TITLE
为何使用英文示例?

### ISSUE THREAD

**Issue by RealXuChe** [huangjj27/async-book#50]
示例已经有翻译了,但是却没有引用翻译版示例,示例注释还是英文.
请问 2223281d76cb91609cd98c25bcab1e318559f67a 为什么要把示例改回英文?

**Comment by huangjj27** [comment]
> 示例已经有翻译了,但是却没有引用翻译版示例,示例注释还是英文.

原本引用的示例翻译程序已经是旧版本了，并且已经没有维护。同时为了同步需要，将使用英文版本。
