### ISSUE TITLE
关于shadow的翻译问题

### ISSUE THREAD

**Issue by oh-wind** [huangjj27/async-book#63]
在[01_chapter.md](https://github.com/huangjj27/async-book/blob/zh-CN/src_zh-CN/04_pinning/01_chapter.md)中提到的
> 另外一个常见错误是忘记影射（shadow）原本的变量

此处翻译是否略有不妥。shadow 做动词时有“遮蔽”的意思，[The book](https://doc.rust-lang.org/book/ch03-01-variables-and-mutability.html?highlight=shadow#shadowing) 中的意思也应该是“遮蔽、覆盖”，而“影射”一词却有“暗指，借此说彼，映射”之义，与此处语境不合，也会增加读者的理解难度（没错，是我(￣┰￣*)）。
在 *The Book* 的[中文译本](https://github.com/KaiserY/trpl-zh-cn)中对 *Shadow* 一词的翻译是 **隐藏**，我们是否需要与他采用相同的翻译，或是其他近义词？

**Comment by huangjj27** [comment]
参考 [如何看待 Rust 这门语言？ - shanewfx的回答 - 知乎](https://www.zhihu.com/question/432640008/answer/1668000615)以及题主的建议，术语 `shadow` 翻译修改为 “遮蔽”
