### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by bxezi** [huangjj27/async-book#83]
[Rust 的异步 vs 其他语言的](https://huangjj27.github.io/async-book/01_getting_started/02_why_async.html#rust-%E7%9A%84%E5%BC%82%E6%AD%A5-vs-%E5%85%B6%E4%BB%96%E8%AF%AD%E8%A8%80%E7%9A%84) 这一节中第一个区别 **Futures are inert** in Rust 被错译成了插入”Rust 中 **插入了Futures**“，inert 的意思是惰性的

**Comment by huangjj27** [comment]
> inert 的意思是惰性的 

感谢指正！
